language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

# This section can be removed when Python 3.7 is more cleanly supported in Travis
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list
  - pip show pandana

script:
  - pycodestyle pandana
  - python setup.py test --pytest-args "--cov pandana --cov-report term-missing"

after_success:
  - coveralls
  - bin/build_docs.sh

env:
  global:
    secure: CMG0rjBgDBNy5FdfXawaaCCJm9ChzHk7e21ywVhIc1jbVS6lMn6bqwKJUnLaJAyjDhhZuxXTcHy+SALJgbzqLrH4GM5hOOL+8Rf4Jf9ESZzTBryvypRecVnUnk63SpJiq2Ki8maNrOcK1IBUAoFhFzptSgE4MDkxZ0LjsDAums8=
